spring:
  main.web-application-type: none
  banner:
    location: classpath:banner.txt
  datasource:
    url: jdbc:postgresql://localhost:54345/testdb
    username: testuser
    password: password

  jpa:
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true #false #--> Better to define SQL output in log to also get the bind parameters
    hibernate:
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
      # Validate the entities against the DB schema at startup (BUT: not vice versa)
      ddl-auto: validate
    properties.hibernate.jdbc.time_zone: UTC
